### ISSUE TITLE
Cubox-i: can't build nv_imx_dec: linux/mxc_v4l2.h: No such file or directory

### ISSUE THREAD

**Issue by abossard** [irtimmer/moonlight-embedded#58]
I followed your instructions and I can't build it on:
> Linux alarm 3.14.14-8-ARCH #1 SMP Fri Oct 24 06:51:22 MDT 2014 armv7l GNU/Linux

With these packages installed:
- gpu-viv-bin-mx6q-fb 
- firmware-brcm43xx 
- imx-vpu firmware-imx 
- v4l-utils 
- libfslvpuwrap
(and of course the base requirements like ant, oracle java and so forth)

limelight compiles and pairs, but can't stream with this error:
```
Exception in thread "main" java.lang.reflect.InvocationTargetException
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:483)
        at com.simontuffs.onejar.Boot.run(Boot.java:342)
        at com.simontuffs.onejar.Boot.main(Boot.java:168)
Caused by: java.lang.NullPointerException
        at com.limelight.binding.PlatformBinding.getVideoDecoderRenderer(Unknown Source)
        at com.limelight.Limelight.startUp(Unknown Source)
        at com.limelight.Limelight.main(Unknown Source)
```

The prebuilt version runs fine, but never displays any video output.

From other threads and how it looks, I think it's currently not working on latest Archlinux on Cubox-i. Or what could I try?

**Comment by irtimmer** [comment]
Kernel versions >3.10 are not supported on imx6

**Comment by rkorn86** [comment]
will there be any support anytime?

**Comment by irtimmer** [comment]
As soon as the needed patches are applied to the kernel (see https://github.com/SolidRun/linux-imx6-3.14/pull/26)

**Comment by rkorn86** [comment]
I applied those patches to my Archlinux (https://github.com/CrawX/PKGBUILDs/tree/wblinux3.14/core/linux-wandboard) Kernel (https://github.com/CrawX/linux-linaro-stable-mx6/commit/0e674c785c17dd4878db3fdd30d315adfc9711a7) running on my Wandboard Quad (imx6 based), but neither get sound, nor video. If you wish, I can send you my console log.
