### ISSUE TITLE
"Read timed out" when trying to start stream.

### ISSUE THREAD

**Issue by Ardnived** [irtimmer/moonlight-embedded#78]
On a Raspberry Pi Model B with Raspbian. I'm able to connect to the internet without issue, and I was able to pair limelight with my desktop. However, when I try to start the stream I get a "Read timed out" error.

I've tried reinstalling NVIDIA GeForce Experience. I tried updating the raspberry pi firmware. But I'm at a bit of a loss as to how to troubleshoot this. Can anyone give me some pointers on what the problem might be or how to go about debugging it?

    Starting Steam
    java.net.SocketTimeoutException: Read timed out
    	at java.net.SocketInputStream.socketRead0(Native Method)
    	at java.net.SocketInputStream.read(SocketInputStream.java:150)
    	at java.net.SocketInputStream.read(SocketInputStream.java:121)
    	at sun.security.ssl.InputRecord.readFully(InputRecord.java:465)
    	at sun.security.ssl.InputRecord.read(InputRecord.java:503)
    	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:954)
    	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1343)
    	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1371)
    	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1355)
    	at com.squareup.okhttp.Connection.upgradeToTls(Connection.java:235)
    	at com.squareup.okhttp.Connection.connect(Connection.java:153)
    	at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:169)
    	at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:119)
    	at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:134)
    	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:314)
    	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:237)
    	at com.squareup.okhttp.Call.getResponse(Call.java:233)
    	at com.squareup.okhttp.Call.execute(Call.java:84)
    	at com.limelight.nvstream.http.NvHTTP.openHttpConnection(Unknown Source)
    	at com.limelight.nvstream.http.NvHTTP.openHttpConnectionToString(Unknown Source)
    	at com.limelight.nvstream.http.NvHTTP.getServerInfo(Unknown Source)
    	at com.limelight.nvstream.NvConnection.startApp(Unknown Source)
    	at com.limelight.nvstream.NvConnection.establishConnection(Unknown Source)
    	at com.limelight.nvstream.NvConnection.access$300(Unknown Source)
    	at com.limelight.nvstream.NvConnection$1.run(Unknown Source)
    	at java.lang.Thread.run(Thread.java:744)
    Read timed out
    Connection Error Starting Steam failed

Occasionally I also get a "handshake_failure" error instead.

    Starting Steam
    javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure
    	at sun.security.ssl.Alerts.getSSLException(Alerts.java:192)
    	at sun.security.ssl.Alerts.getSSLException(Alerts.java:154)
    	at sun.security.ssl.SSLSocketImpl.recvAlert(SSLSocketImpl.java:1991)
    	at sun.security.ssl.SSLSocketImpl.readRecord(SSLSocketImpl.java:1104)
    	at sun.security.ssl.SSLSocketImpl.performInitialHandshake(SSLSocketImpl.java:1343)
    	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1371)
    	at sun.security.ssl.SSLSocketImpl.startHandshake(SSLSocketImpl.java:1355)
    	at com.squareup.okhttp.Connection.upgradeToTls(Connection.java:235)
    	at com.squareup.okhttp.Connection.connect(Connection.java:153)
    	at com.squareup.okhttp.Connection.connectAndSetOwner(Connection.java:169)
    	at com.squareup.okhttp.OkHttpClient$1.connectAndSetOwner(OkHttpClient.java:119)
    	at com.squareup.okhttp.internal.http.RouteSelector.next(RouteSelector.java:134)
    	at com.squareup.okhttp.internal.http.HttpEngine.connect(HttpEngine.java:314)
    	at com.squareup.okhttp.internal.http.HttpEngine.sendRequest(HttpEngine.java:237)
    	at com.squareup.okhttp.Call.getResponse(Call.java:233)
    	at com.squareup.okhttp.Call.execute(Call.java:84)
    	at com.limelight.nvstream.http.NvHTTP.openHttpConnection(Unknown Source)
    	at com.limelight.nvstream.http.NvHTTP.getAppList(Unknown Source)
    	at com.limelight.nvstream.http.NvHTTP.getApp(Unknown Source)
    	at com.limelight.nvstream.NvConnection.startApp(Unknown Source)
    	at com.limelight.nvstream.NvConnection.establishConnection(Unknown Source)
    	at com.limelight.nvstream.NvConnection.access$300(Unknown Source)
    	at com.limelight.nvstream.NvConnection$1.run(Unknown Source)
    	at java.lang.Thread.run(Thread.java:744)
    Received fatal alert: handshake_failure
    Connection Error Starting Steam failed

**Comment by irtimmer** [comment]
Looks like connection can't be made because of incorrect address or firewall
